
export const firebaseConfig = {
  apiKey: "AIzaSyA35D1SwQdAPOAp-wxRYsezWQI7rvIPQAY",
  authDomain: "counting-system.firebaseapp.com",
  projectId: "counting-system",
  storageBucket: "counting-system.appspot.com",
  messagingSenderId: "726733968843",
  appId: "1:726733968843:web:d68da6c09a4a1aac7fd24e",
};

export const BASE_PATH = '';
export const EXTERNAL_PATH = 'distrito-'
export const EXTERNAL_PATH_ENDPOINT = 'LINGAYEN_PANGASINAN'

export const arr =[ 
    "AGUILAR",
    "ALITAYA",
    "ANGIO",
    "AWAY",
    "BAAY EXT",
    "BACABAC",
    "BALOCOC",
    "BALOLING",
    "BANAYBAYAN EXT",
    "BATENG",
    "BINDAY",
    "BINMALEY",
    "BISBISOCOL",
    "BOLO",
    "BONUAN",
    "BUGALLON",
    "CALASIAO",
    "CALIT",
    "CALMAY",
    "CARAEL",
    "COLISAO",
    "DAGUPAN CITY",
    "DAVID",
    "DOMALANDAN",
    "DULAG",
    "AMBUETEL",
    "HACIENDA",
    "HAWAY",
    "INMALOG",
    "LAGUIT CENTRO",
    "LEET",
    "LINGAYEN",
    "LIBSONG EAST EXT",
    "OSIEM ANTIMANO EXT",
    "LOBONG",
    "LONGOS CALASIAO EXT",
    "LONGOS SAN FABIAN EXT",
    "LUYAN",
    "MAAMBAL",
    "MAASIN EXT",
    "MABILAO",
    "MAGTAKING",
    "MALINDONG EXT",
    "MAMALINGLING",
    "MANAOAG",
    "MANAOAG DOS",
    "MANGALDAN",
    "MAPANDAN",
    "MATALAVA",
    "NIÑOY",
    "PANGAPISAN NORTH",
    "PALUA EXT",
    "PUGARO",
    "QUETEGAN",
    "ROSARIO",
    "SALOMAGUE",
    "SAN FABIAN",
    "SAN JACINTO",
    "SAN RAMON EXT",
    "TALIBAEW EXT",
    "TULONG"
        ] ;

        
export const arr_external = [
  "LINGAYEN PANGASINAN",
  "ALAMINOS CITY PANGASINAN",
  "URDANETA CITY PANGASINAN",
  "SAN CARLOS CITY PANGASINAN",
  "ROSALES PANGASINAN",
  "LA UNION",
  "ILOCOS SUR",
  "BATAC CITY ILOCOS NORTES",
  "LAOAG CITY ILOCOS NORTE",
  "BENGUET",
  "MOUNTAIN PROVINCE",
  "ABRA",
  "CANDON CITY ILOCOS SUR"
];
